#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import argparse
import datetime

from diariolib import client

right_now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

parser = argparse.ArgumentParser(
    prog="eldiario",
    description="A CLI diary app.",
    formatter_class=argparse.RawDescriptionHelpFormatter,
    epilog="""See link below for more info:
Update me with the bitbucket URL.""")

group = parser.add_mutually_exclusive_group()

group.add_argument('-n',
                   '--new',
                   action='store_true',
                   help='create new note at current time')
group.add_argument('-e', '--edit', metavar='ID', help='edit an existing note')
# The listing should show also the IDs.
group.add_argument('-l',
                   '--list',
                   action='store_true',
                   help='list existing notes')
group.add_argument('-d',
                   '--delete',
                   metavar='ID',
                   nargs='+',
                   help='delete existing notes')
# sync on every new entries and edits to the backing store

args = parser.parse_args()
diaryapp = client.ElDiario(args)

if not diaryapp.backend_running():
    sys.exit("Connection Error")

# This will notbe the default, instead will be --new
if len(sys.argv) < 2:
    parser.print_usage()
elif args.list:
    diaryapp.list_entry()
elif args.new:
    diaryapp.new_entry(right_now)
elif args.edit:
    diaryapp.update_entry(args.edit)
elif args.delete:
    diaryapp.delete_entry(args.delete)
